from enum import Enum

class ReasonCode(str, Enum):
    NO_FACE_DETECTED = "NO_FACE_DETECTED"
    GROUP_PHOTO_DETECTED = "GROUP_PHOTO_DETECTED"
    NOT_FULL_BODY = "NOT_FULL_BODY"
    BACK_VIEW_NOT_DETECTED = "BACK_VIEW_NOT_DETECTED"
    ANGLE_MISMATCH = "ANGLE_MISMATCH"
    PARTIAL_TURN = "PARTIAL_TURN"
    IMAGE_BLURRY = "IMAGE_BLURRY"
    POOR_LIGHTING = "POOR_LIGHTING"
    EYEWEAR_DETECTED = "EYEWEAR_DETECTED"
    EYES_CLOSED = "EYES_CLOSED"
    FACE_PARTIALLY_COVERED = "FACE_PARTIALLY_COVERED"
    HEAVY_EDITING_DETECTED = "HEAVY_EDITING_DETECTED"
    FACE_NOT_CENTERED = "FACE_NOT_CENTERED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    CORRUPT_IMAGE = "CORRUPT_IMAGE"
    RESOLUTION_TOO_LOW = "RESOLUTION_TOO_LOW"
    EXPLICIT_CONTENT_DETECTED = "EXPLICIT_CONTENT_DETECTED"
    MIRROR_SELFIE_DETECTED = "MIRROR_SELFIE_DETECTED"
    SIDE_PROFILE_FULL_BODY = "SIDE_PROFILE_FULL_BODY"
    CARTOON_OR_ART_DETECTED = "CARTOON_OR_ART_DETECTED"
    BACKGROUND_CLUTTERED = "BACKGROUND_CLUTTERED"
    EXPRESSION_NOT_NEUTRAL = "EXPRESSION_NOT_NEUTRAL"
    CAMERA_NOT_EYE_LEVEL = "CAMERA_NOT_EYE_LEVEL"
    UNEVEN_LIGHTING = "UNEVEN_LIGHTING"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"

class VerificationError(Exception):
    def __init__(self, code: str, message: str):
        self.code = code
        self.message = message
        super().__init__(code, message)
